import groovy.json.JsonSlurper

node {
    
    stage('runParallelProductJobs') {
        
        try {
            def receivedJson = System.properties['UPDATE_LIST_JSON']
            println "Received Json: " + receivedJson
            def jsonSlurper = new JsonSlurper()
            def resultJson = jsonSlurper.parseText(receivedJson)
            jsonSlurper = null
            
            def branches = [:]
            
            for (int index = 0; index < resultJson.size(); index++) {
                String jobName = resultJson[index].jobName;
                String fileUrl = resultJson[index].updateFileUrl;
                String fileName = resultJson[index].updateFileName;
                branches["branch:"+ jobName] = {build job: jobName, parameters: [[$class: 'StringParameterValue', name: 'UPDATE_FILE_URL', value: fileUrl], [$class: 'StringParameterValue', name: 'UPDATE_FILE_NAME', value: fileName]]};
                println "Added parallel ECS slave to run, jobName: " + jobName + ", updateFileUrl: " + fileUrl + ", updateFileName: " + fileName
            }
            resultJson = null
            
            parallel branches
        } catch(Exception e) {
            println "ERROR: " + e
        }
    }

}
